// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: api/metrics.proto

package metricspb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// MType задаёт тип метрики.
type Metric_MType int32

const (
	Metric_GAUGE   Metric_MType = 0
	Metric_COUNTER Metric_MType = 1
)

// Enum value maps for Metric_MType.
var (
	Metric_MType_name = map[int32]string{
		0: "GAUGE",
		1: "COUNTER",
	}
	Metric_MType_value = map[string]int32{
		"GAUGE":   0,
		"COUNTER": 1,
	}
)

func (x Metric_MType) Enum() *Metric_MType {
	p := new(Metric_MType)
	*p = x
	return p
}

func (x Metric_MType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Metric_MType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_metrics_proto_enumTypes[0].Descriptor()
}

func (Metric_MType) Type() protoreflect.EnumType {
	return &file_api_metrics_proto_enumTypes[0]
}

func (x Metric_MType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Metric определяет единичную метрику.
type Metric struct {
	state            protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id    string                 `protobuf:"bytes,1,opt,name=id,proto3"`
	xxx_hidden_Type  Metric_MType           `protobuf:"varint,2,opt,name=type,proto3,enum=metrics.Metric_MType"`
	xxx_hidden_Delta int64                  `protobuf:"varint,3,opt,name=delta,proto3"`
	xxx_hidden_Value float64                `protobuf:"fixed64,4,opt,name=value,proto3"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Metric) Reset() {
	*x = Metric{}
	mi := &file_api_metrics_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Metric) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metric) ProtoMessage() {}

func (x *Metric) ProtoReflect() protoreflect.Message {
	mi := &file_api_metrics_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Metric) GetId() string {
	if x != nil {
		return x.xxx_hidden_Id
	}
	return ""
}

func (x *Metric) GetType() Metric_MType {
	if x != nil {
		return x.xxx_hidden_Type
	}
	return Metric_GAUGE
}

func (x *Metric) GetDelta() int64 {
	if x != nil {
		return x.xxx_hidden_Delta
	}
	return 0
}

func (x *Metric) GetValue() float64 {
	if x != nil {
		return x.xxx_hidden_Value
	}
	return 0
}

func (x *Metric) SetId(v string) {
	x.xxx_hidden_Id = v
}

func (x *Metric) SetType(v Metric_MType) {
	x.xxx_hidden_Type = v
}

func (x *Metric) SetDelta(v int64) {
	x.xxx_hidden_Delta = v
}

func (x *Metric) SetValue(v float64) {
	x.xxx_hidden_Value = v
}

type Metric_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id   string
	Type Metric_MType
	// Поле delta используется для метрик-счётчиков.
	Delta int64
	// Поле value используется для метрик-измерителей.
	Value float64
}

func (b0 Metric_builder) Build() *Metric {
	m0 := &Metric{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Id = b.Id
	x.xxx_hidden_Type = b.Type
	x.xxx_hidden_Delta = b.Delta
	x.xxx_hidden_Value = b.Value
	return m0
}

// UpdateMetricsRequest содержит список метрик для обновления.
type UpdateMetricsRequest struct {
	state              protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Metrics *[]*Metric             `protobuf:"bytes,1,rep,name=metrics,proto3"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *UpdateMetricsRequest) Reset() {
	*x = UpdateMetricsRequest{}
	mi := &file_api_metrics_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMetricsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMetricsRequest) ProtoMessage() {}

func (x *UpdateMetricsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_metrics_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *UpdateMetricsRequest) GetMetrics() []*Metric {
	if x != nil {
		if x.xxx_hidden_Metrics != nil {
			return *x.xxx_hidden_Metrics
		}
	}
	return nil
}

func (x *UpdateMetricsRequest) SetMetrics(v []*Metric) {
	x.xxx_hidden_Metrics = &v
}

type UpdateMetricsRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Metrics []*Metric
}

func (b0 UpdateMetricsRequest_builder) Build() *UpdateMetricsRequest {
	m0 := &UpdateMetricsRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Metrics = &b.Metrics
	return m0
}

// UpdateMetricsResponse — пустой ответ для подтверждения успешного обновления.
type UpdateMetricsResponse struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMetricsResponse) Reset() {
	*x = UpdateMetricsResponse{}
	mi := &file_api_metrics_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMetricsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMetricsResponse) ProtoMessage() {}

func (x *UpdateMetricsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_metrics_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type UpdateMetricsResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 UpdateMetricsResponse_builder) Build() *UpdateMetricsResponse {
	m0 := &UpdateMetricsResponse{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

var File_api_metrics_proto protoreflect.FileDescriptor

const file_api_metrics_proto_rawDesc = "" +
	"\n" +
	"\x11api/metrics.proto\x12\ametrics\"\x90\x01\n" +
	"\x06Metric\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12)\n" +
	"\x04type\x18\x02 \x01(\x0e2\x15.metrics.Metric.MTypeR\x04type\x12\x14\n" +
	"\x05delta\x18\x03 \x01(\x03R\x05delta\x12\x14\n" +
	"\x05value\x18\x04 \x01(\x01R\x05value\"\x1f\n" +
	"\x05MType\x12\t\n" +
	"\x05GAUGE\x10\x00\x12\v\n" +
	"\aCOUNTER\x10\x01\"A\n" +
	"\x14UpdateMetricsRequest\x12)\n" +
	"\ametrics\x18\x01 \x03(\v2\x0f.metrics.MetricR\ametrics\"\x17\n" +
	"\x15UpdateMetricsResponse2Y\n" +
	"\aMetrics\x12N\n" +
	"\rUpdateMetrics\x12\x1d.metrics.UpdateMetricsRequest\x1a\x1e.metrics.UpdateMetricsResponseBBZ@github.com/xhrobj/go-metrics-and-alerts/internal/proto;metricspbb\x06proto3"

var file_api_metrics_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_metrics_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_api_metrics_proto_goTypes = []any{
	(Metric_MType)(0),             // 0: metrics.Metric.MType
	(*Metric)(nil),                // 1: metrics.Metric
	(*UpdateMetricsRequest)(nil),  // 2: metrics.UpdateMetricsRequest
	(*UpdateMetricsResponse)(nil), // 3: metrics.UpdateMetricsResponse
}
var file_api_metrics_proto_depIdxs = []int32{
	0, // 0: metrics.Metric.type:type_name -> metrics.Metric.MType
	1, // 1: metrics.UpdateMetricsRequest.metrics:type_name -> metrics.Metric
	2, // 2: metrics.Metrics.UpdateMetrics:input_type -> metrics.UpdateMetricsRequest
	3, // 3: metrics.Metrics.UpdateMetrics:output_type -> metrics.UpdateMetricsResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_api_metrics_proto_init() }
func file_api_metrics_proto_init() {
	if File_api_metrics_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_metrics_proto_rawDesc), len(file_api_metrics_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_metrics_proto_goTypes,
		DependencyIndexes: file_api_metrics_proto_depIdxs,
		EnumInfos:         file_api_metrics_proto_enumTypes,
		MessageInfos:      file_api_metrics_proto_msgTypes,
	}.Build()
	File_api_metrics_proto = out.File
	file_api_metrics_proto_goTypes = nil
	file_api_metrics_proto_depIdxs = nil
}
