sonar.organization=xhrobj
sonar.projectKey=xhrobj_go-metrics-and-alerts

sonar.sources=.
sonar.tests=.
sonar.test.inclusions=**/*_test.go

sonar.go.coverage.reportPaths=coverage.out

sonar.coverage.exclusions=\
  cmd/**,\
  internal/config/**,\
  internal/agent/config/**,\
  internal/handler/config/**,\
  internal/logger/**,\
  internal/model/**,\
  migrations/**,\
  **/*_test.go

# Фикстуры staticlint содержат намеренно плохой код для тестов анализатора
sonar.exclusions=\
  cmd/staticlint/noosexit/testdata/**

# CPD-исключения оставлены здесь для видимости как намерение.
# Фактически из этого файла они не сработали и были настроены в UI SonarCloud
sonar.cpd.exclusions=\
  **/*_test.go,\
  migrations/**
