package main

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/printer"
	"go/token"
	"io/fs"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

const (
	resetDirective    = "generate:reset"
	generatedFile     = "reset.gen.go"
	generatedFileHead = "// Code generated by reset; (+_+)~ DON'T EDIT PLZ."
)

type packageInfo struct {
	Name    string
	Structs []resetStruct
}

type resetStruct struct {
	Name   string
	Fields []resetField
}

type resetField struct {
	Name string
	Type ast.Expr
}

func Generate(root string) ([]string, error) {

	// 1. найти пакеты со структурами с "аннотацией" // generate:reset
	packages, err := collectPackages(root)
	if err != nil {
		return nil, err
	}

	dirs := make([]string, 0, len(packages))
	for dir := range packages {
		dirs = append(dirs, dir)
	}
	sort.Strings(dirs)

	generatedFiles := make([]string, 0, len(dirs))

	for _, dir := range dirs {
		// 2. построить для найденных структур текст Go-кода с методами Reset()
		src, err := buildGeneratedFile(packages[dir])
		if err != nil {
			return nil, fmt.Errorf("build %s: %w", dir, err)
		}

		// 3. отформатировать и записать reset.gen.go в нужные пакеты
		path := filepath.Join(dir, generatedFile)
		if err := os.WriteFile(path, src, 0644); err != nil {
			return nil, fmt.Errorf("write %s: %w", path, err)
		}

		generatedFiles = append(generatedFiles, path)
	}

	return generatedFiles, nil
}

func collectPackages(root string) (map[string]*packageInfo, error) {
	packages := make(map[string]*packageInfo)
	fset := token.NewFileSet()

	err := filepath.WalkDir(root, func(path string, entry fs.DirEntry, walkErr error) error {
		if walkErr != nil {
			return walkErr
		}

		if entry.IsDir() {
			if path != root && shouldSkipDir(entry.Name()) {
				return filepath.SkipDir
			}

			return nil
		}

		if !isGoSource(path) {
			return nil
		}

		file, err := parser.ParseFile(fset, path, nil, parser.ParseComments)
		if err != nil {
			return fmt.Errorf("parse %s: %w", path, err)
		}

		structs := findResetStructs(file)
		if len(structs) == 0 {
			return nil
		}

		dir := filepath.Dir(path)
		info := packages[dir]
		if info == nil {
			info = &packageInfo{Name: file.Name.Name}
			packages[dir] = info
		}

		if info.Name != file.Name.Name {
			return fmt.Errorf("package mismatch in %s: got %s, want %s", path, file.Name.Name, info.Name)
		}

		info.Structs = append(info.Structs, structs...)

		return nil
	})

	if err != nil {
		return nil, err
	}

	return packages, nil
}

func shouldSkipDir(name string) bool {
	switch name {
	case ".git", ".github", "vendor", "testdata", "migrations":
		return true
	default:
		return false
	}
}

func isGoSource(path string) bool {
	name := filepath.Base(path)

	return strings.HasSuffix(name, ".go") &&
		!strings.HasSuffix(name, "_test.go") &&
		name != generatedFile
}

func findResetStructs(file *ast.File) []resetStruct {
	var structs []resetStruct

	for _, decl := range file.Decls {
		genDecl, ok := decl.(*ast.GenDecl)
		if !ok || genDecl.Tok != token.TYPE {
			continue
		}

		declMarked := hasResetDirective(genDecl.Doc)

		for _, spec := range genDecl.Specs {
			typeSpec, ok := spec.(*ast.TypeSpec)
			if !ok {
				continue
			}

			structType, ok := typeSpec.Type.(*ast.StructType)
			if !ok {
				continue
			}

			if !declMarked && !hasResetDirective(typeSpec.Doc) {
				continue
			}

			structs = append(structs, resetStruct{
				Name:   typeSpec.Name.Name,
				Fields: collectFields(structType),
			})
		}
	}

	return structs
}

func hasResetDirective(group *ast.CommentGroup) bool {
	if group == nil {
		return false
	}

	for _, comment := range group.List {
		text := strings.TrimSpace(comment.Text)
		text = strings.TrimPrefix(text, "//")
		text = strings.TrimPrefix(text, "/*")
		text = strings.TrimSuffix(text, "*/")
		text = strings.TrimSpace(text)

		if strings.ReplaceAll(text, " ", "") == resetDirective {
			return true
		}
	}

	return false
}

func collectFields(structType *ast.StructType) []resetField {
	var fields []resetField

	for _, field := range structType.Fields.List {
		for _, name := range field.Names {
			fields = append(fields, resetField{
				Name: name.Name,
				Type: field.Type,
			})
		}
	}

	return fields
}

func buildGeneratedFile(info *packageInfo) ([]byte, error) {
	var builder strings.Builder

	fmt.Fprintf(&builder, "%s\n\n", generatedFileHead)
	fmt.Fprintf(&builder, "package %s\n\n", info.Name)

	for i, resetStruct := range info.Structs {
		if i > 0 {
			builder.WriteString("\n")
		}

		if err := writeResetMethod(&builder, resetStruct); err != nil {
			return nil, err
		}
	}

	formatted, err := format.Source([]byte(builder.String()))
	if err != nil {
		return nil, fmt.Errorf("format generated source: %w\n%s", err, builder.String())
	}

	return formatted, nil
}

func writeResetMethod(builder *strings.Builder, resetStruct resetStruct) error {
	fmt.Fprintf(builder, "func (s *%s) Reset() {\n", resetStruct.Name)

	builder.WriteString("\tif s == nil {\n")
	builder.WriteString("\t\treturn\n")
	builder.WriteString("\t}\n\n")

	for _, field := range resetStruct.Fields {
		if err := writeResetField(builder, field); err != nil {
			return err
		}
	}

	builder.WriteString("}\n")

	return nil
}

func writeResetField(builder *strings.Builder, field resetField) error {
	switch fieldType := field.Type.(type) {
	case *ast.Ident:
		return writeIdentReset(builder, field.Name, fieldType)
	case *ast.StarExpr:
		return writePointerReset(builder, field.Name, fieldType)
	case *ast.ArrayType:
		return writeArrayReset(builder, field.Name, fieldType)
	case *ast.MapType:
		fmt.Fprintf(builder, "\tclear(s.%s)\n", field.Name)
		return nil
	default:
		return writeZeroValueReset(builder, field.Name, field.Type)
	}
}

func writeIdentReset(builder *strings.Builder, fieldName string, fieldType *ast.Ident) error {
	zeroValue, ok := primitiveZeroValue(fieldType.Name)
	if ok {
		fmt.Fprintf(builder, "\ts.%s = %s\n", fieldName, zeroValue)
		return nil
	}

	typeName, err := exprString(fieldType)
	if err != nil {
		return err
	}

	fmt.Fprintf(builder, "\tif resetter, ok := any(&s.%s).(interface{ Reset() }); ok {\n", fieldName)

	builder.WriteString("\t\tresetter.Reset()\n")
	builder.WriteString("\t} else {\n")

	fmt.Fprintf(builder, "\t\tvar zero%s %s\n", fieldName, typeName)
	fmt.Fprintf(builder, "\t\ts.%s = zero%s\n", fieldName, fieldName)

	builder.WriteString("\t}\n")

	return nil
}

func writePointerReset(builder *strings.Builder, fieldName string, fieldType *ast.StarExpr) error {
	zeroValue, ok := primitivePointerZeroValue(fieldType)
	if ok {
		fmt.Fprintf(builder, "\tif s.%s != nil {\n", fieldName)
		fmt.Fprintf(builder, "\t\t*s.%s = %s\n", fieldName, zeroValue)
		builder.WriteString("\t}\n")
		return nil
	}

	fmt.Fprintf(builder, "\tif s.%s != nil {\n", fieldName)
	fmt.Fprintf(builder, "\t\tif resetter, ok := any(s.%s).(interface{ Reset() }); ok {\n", fieldName)

	builder.WriteString("\t\t\tresetter.Reset()\n")
	builder.WriteString("\t\t}\n")
	builder.WriteString("\t}\n")

	return nil
}

func writeArrayReset(builder *strings.Builder, fieldName string, fieldType *ast.ArrayType) error {
	if fieldType.Len == nil {
		fmt.Fprintf(builder, "\ts.%s = s.%s[:0]\n", fieldName, fieldName)
		return nil
	}

	return writeZeroValueReset(builder, fieldName, fieldType)
}

func writeZeroValueReset(builder *strings.Builder, fieldName string, expr ast.Expr) error {
	typeName, err := exprString(expr)
	if err != nil {
		return err
	}

	fmt.Fprintf(builder, "\tvar zero%s %s\n", fieldName, typeName)
	fmt.Fprintf(builder, "\ts.%s = zero%s\n", fieldName, fieldName)

	return nil
}

func primitivePointerZeroValue(fieldType *ast.StarExpr) (string, bool) {
	ident, ok := fieldType.X.(*ast.Ident)
	if !ok {
		return "", false
	}

	return primitiveZeroValue(ident.Name)
}

func primitiveZeroValue(typeName string) (string, bool) {
	switch typeName {
	case "string":
		return `""`, true
	case "bool":
		return "false", true
	case "int", "int8", "int16", "int32", "int64",
		"uint", "uint8", "uint16", "uint32", "uint64", "uintptr",
		"byte", "rune", "float32", "float64", "complex64", "complex128":
		return "0", true
	default:
		return "", false
	}
}

func exprString(expr ast.Expr) (string, error) {
	var builder bytes.Buffer

	if err := printer.Fprint(&builder, token.NewFileSet(), expr); err != nil {
		return "", err
	}

	return builder.String(), nil
}
