// Code generated by reset; (+_+)~ DON'T EDIT PLZ.

package sample

func (s *ResettableState) Reset() {
	if s == nil {
		return
	}

	s.Number = 0
	s.Text = ""
	s.Enabled = false
	if s.TextPtr != nil {
		*s.TextPtr = ""
	}
	if s.CounterPtr != nil {
		*s.CounterPtr = 0
	}
	s.Values = s.Values[:0]
	clear(s.Labels)
	if s.Child != nil {
		if resetter, ok := any(s.Child).(interface{ Reset() }); ok {
			resetter.Reset()
		}
	}
}
