name: (-_-) Go CI

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  go-ci:
    name: Quality checks -> lint, build, vet, test
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: true

      - name: (^_^) Run golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: v2.11

      - name: (^_^) Run build
        run: make build

      - name: (^_^) Vet
        run: make vet

      - name: (^_^) Run tests --race
        run: make test-race
